name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create symlink # Can be removed as soon as this is fixed: https://github.com/googleapis/release-please-action/issues/741
        run: |
          ln -s runo/Chart.yaml
          ln -s runo/CHANGELOG.md
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          path: runo
          release-type: helm
      - name: Configure Git
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        if: ${{ steps.release.outputs.release_created }}
        uses: azure/setup-helm@v4
      - name: Run chart-releaser
        if: ${{ steps.release.outputs.release_created }}
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: .
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"